### ISSUE TITLE
CSRF checking in admin.py

### ISSUE THREAD

**Issue by gengkev** [tjcsl/ctf-platform#26]
Is there a reason why `admin_score_adjust` doesn't appear to be annotated with `@csrf_check`, unlike other functions in the same file? (I'm not sure whether this is also covered by the CSRF code in `app.py`.)

https://github.com/TJCSec/ctf-platform/blob/master/modules/admin.py

**Comment by sdamashek** [comment]
The others are only annotated with `@csrf_check` because they're GET requests, which don't require csrf checking by default. `admin_score_adjust` is a POST request, which already has code to require csrf tokens by default (https://github.com/TJCSec/ctf-platform/blob/bb1a39f4f7d94979f99ffbd164547a8a4c87e7a3/app.py#L354-L361).

**Comment by pefoley2** [comment]
Maybe worth adding a comment?

**Comment by gengkev** [comment]
Oh, I guess the `request.form` access ensures a POST request (or PUT, but that's not easily CSRF-able). But am I missing something, or shouldn't there be a CSRF token in the corresponding `<form>` at https://github.com/TJCSec/ctf-platform/blob/master/templates/admin/team.html ?
