### ISSUE TITLE
Fix animations on problems thing

### ISSUE THREAD

**Issue by laudiacay** [tjcsl/ctf-platform#4]
opening and closing for the most part look really really really nice, but when you solve one it can sometimes freak out. Also reloading looks weird.

**Comment by an-empty-string** [comment]
solving one will go to the server and reload the page, so that's expected. what should happen on reloading? restore the previous collapsed/uncollapsed state? this might not make sense without a "reset" button -- currently the ui defaults to unsolved problems being open/uncollapsed and solved problems being closed/collapsed.
